# Generated by Django 5.1.2 on 2024-10-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_lastname_users_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='firtsname',
        ),
    ]
