# Generated by Django 5.1.2 on 2024-10-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usersdetails_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='addres',
            field=models.TextField(default='null', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='miniatura/'),
        ),
    ]
